rmarkdown::render('./AdvPD/AdvPD1a/labAdvPD1aRev.Rmd')
rmarkdown::render('./AdvPD/AdvPD1b/labAdvPD1bRev.Rmd')
rmarkdown::render('./AdvPD/AdvPD2a/labAdvPD2aRev.Rmd')
rmarkdown::render('./AdvPD/AdvPD2b/labAdvPD2bRev.Rmd')
rmarkdown::render('./AdvPD/labAdvPD7Rev.Rmd')
rmarkdown::render('./AdvPD/labAdvPD8Rev.Rmd')
rmarkdown::render('./AdvPD/labAdvPD9Rev.Rmd')
rmarkdown::render('./AdvPD/labAdvPD10Rev.Rmd')
rmarkdown::render('./AdvPD/labAdvPD11Rev.Rmd')
rmarkdown::render('./AdvPD/labAdvPD12Rev.Rmd')
rmarkdown::render('./AdvPD/labAdvPD13Rev.Rmd')
rmarkdown::render('./AdvPD/labAdvPD14Rev.Rmd')
rmarkdown::render('./AdvPD/labAdvPD15Rev.Rmd')

rmarkdown::render('./unit_1/lab1a/lab1aRev.Rmd')
rmarkdown::render('./unit_1/lab1b/lab1bRev.Rmd')
rmarkdown::render('./unit_1/lab1c/lab1cRev.Rmd')
rmarkdown::render('./unit_1/lab1d/lab1dRev.Rmd')
rmarkdown::render('./unit_1/lab1e/lab1eRev.Rmd')
rmarkdown::render('./unit_1/lab1f/lab1fRev.Rmd')
rmarkdown::render('./unit_1/lab1g/lab1gRev.Rmd')
rmarkdown::render('./unit_1/lab1h/lab1hRev.Rmd')
rmarkdown::render('./unit_1/pdlab1d/pdlab1dRev.Rmd')
rmarkdown::render('./unit_1/pdlab1e/pdlab1eRev.Rmd')

rmarkdown::render('./unit_2/lab2a/lab2aRev.Rmd')
rmarkdown::render('./unit_2/lab2b/lab2bRev.Rmd')
rmarkdown::render('./unit_2/lab2c/lab2cRev.Rmd')
rmarkdown::render('./unit_2/lab2d/lab2dRev.Rmd')
rmarkdown::render('./unit_2/lab2e/lab2eRev.Rmd')
rmarkdown::render('./unit_2/lab2f/lab2fRev.Rmd')
rmarkdown::render('./unit_2/lab2g/lab2gRev.Rmd')
rmarkdown::render('./unit_2/lab2h/lab2hRev.Rmd')
rmarkdown::render('./unit_2/lab2i/lab2iRev.Rmd')

rmarkdown::render('./unit_3/lab3a/lab3aRev.Rmd')
rmarkdown::render('./unit_3/lab3b/lab3bRev.Rmd')
rmarkdown::render('./unit_3/lab3c/lab3cRev.Rmd')
rmarkdown::render('./unit_3/lab3d/lab3dRev.Rmd')
rmarkdown::render('./unit_3/lab3e/lab3eRev.Rmd')
rmarkdown::render('./unit_3/lab3f/lab3fRev.Rmd')

rmarkdown::render('./unit_4/lab4a/lab4aRev.Rmd')
rmarkdown::render('./unit_4/lab4b/lab4bRev.Rmd')
rmarkdown::render('./unit_4/lab4c/lab4cRev.Rmd')
rmarkdown::render('./unit_4/lab4d/lab4dRev.Rmd')
rmarkdown::render('./unit_4/lab4e/lab4eRev.Rmd')
rmarkdown::render('./unit_4/lab4f/lab4fRev.Rmd')
rmarkdown::render('./unit_4/lab4g/lab4gRev.Rmd')
rmarkdown::render('./unit_4/lab4h/lab4hRev.Rmd')

